### ISSUE TITLE
a couple of warnings

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/zc.relation#9] opened 2021-04-20 14:39 UTC
```
about to run tox for zopefoundation/zc.relation, 217 of 287
no previously-included directories found matching 'mr.developer.addon'
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
__pycache__.six.cpython-36: module references __path__
warning: no files found matching '*.bat' under directory 'docs'
warning: no files found matching '*.py' under directory 'docs'
warning: no files found matching '*.rst' under directory 'docs'
warning: no files found matching '*.txt' under directory 'docs'
warning: no files found matching 'Makefile' under directory 'docs'
warning: no files found matching '*.gif' under directory 'src'
warning: no files found matching '*.pt' under directory 'src'
warning: no files found matching '*.xml' under directory 'src'
warning: no files found matching '*.zcml' under directory 'src'
zip_safe flag not set; analyzing archive contents...
warning: no files found matching '*.bat' under directory 'docs'
warning: no files found matching '*.txt' under directory 'docs'
warning: no files found matching 'Makefile' under directory 'docs'
warning: no files found matching '*.pt' under directory 'src'
warning: no files found matching '*.zcml' under directory 'src'
  File "build/bdist.linux-x86_64/egg/zope/testrunner/tests/testrunner-ex/sample2/badsyntax.py", line 16
    importx unittest  # noqa: E999
                   ^
SyntaxError: invalid syntax

  File "/home/jugmac00/All/output_zope/zopefoundation/zc.relation/.tox/4/py36/eggs/tmplnfhqkoy/zope.testrunner-5.3.0-py3.6.egg/zope/testrunner/tests/testrunner-ex/sample2/badsyntax.py", line 16
    importx unittest  # noqa: E999
                   ^
SyntaxError: invalid syntax

warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
warning: no previously-included files matching 'appveyor.yml' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'benchmarks'
warning: no files found matching '*.pt' under directory 'src'
warning: no files found matching '*.rst' under directory 'src'
warning: no files found matching '*.zcml' under directory 'src'
warning: no files found matching '*.rst'
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

warning: no files found matching '*' under directory 'transaction'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
warning: no previously-included files found matching 'setup.pyc'
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
zip_safe flag not set; analyzing archive contents...
pycparser.ply.__pycache__.lex.cpython-36: module references __file__
pycparser.ply.__pycache__.lex.cpython-36: module MAY be using inspect.getsourcefile
pycparser.ply.__pycache__.ygen.cpython-36: module references __file__
pycparser.ply.__pycache__.yacc.cpython-36: module references __file__
pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.getsourcefile
pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.stack
no previously-included directories found matching 'terryfy'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'persistent/__pycache__'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
warning: no previously-included files matching 'appveyor.yml' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'benchmarks'
warning: no previously-included files found matching 'setup.pyc'
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
zip_safe flag not set; analyzing archive contents...
pycparser.ply.__pycache__.lex.cpython-36: module references __file__
pycparser.ply.__pycache__.lex.cpython-36: module MAY be using inspect.getsourcefile
pycparser.ply.__pycache__.ygen.cpython-36: module references __file__
pycparser.ply.__pycache__.yacc.cpython-36: module references __file__
pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.getsourcefile
pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.stack
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*#' found anywhere in distribution
warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
In file included from src/BTrees/_LQBTree.c:44:0:
src/BTrees/BTreeModuleTemplate.c:103:1: warning: ‘ulonglong_check’ defined but not used [-Wunused-function]
 ulonglong_check(PyObject *ob)
 ^~~~~~~~~~~~~~~
In file included from src/BTrees/_QOBTree.c:42:0:
src/BTrees/BTreeModuleTemplate.c:209:1: warning: ‘longlong_convert’ defined but not used [-Wunused-function]
 longlong_convert(PyObject *ob, PY_LONG_LONG *value)
 ^~~~~~~~~~~~~~~~
src/BTrees/BTreeModuleTemplate.c:201:1: warning: ‘longlong_as_object’ defined but not used [-Wunused-function]
 longlong_as_object(PY_LONG_LONG val)
 ^~~~~~~~~~~~~~~~~~
src/BTrees/BTreeModuleTemplate.c:132:1: warning: ‘longlong_check’ defined but not used [-Wunused-function]
 longlong_check(PyObject *ob)
 ^~~~~~~~~~~~~~
In file included from src/BTrees/_QQBTree.c:45:0:
src/BTrees/BTreeModuleTemplate.c:209:1: warning: ‘longlong_convert’ defined but not used [-Wunused-function]
 longlong_convert(PyObject *ob, PY_LONG_LONG *value)
 ^~~~~~~~~~~~~~~~
src/BTrees/BTreeModuleTemplate.c:201:1: warning: ‘longlong_as_object’ defined but not used [-Wunused-function]
 longlong_as_object(PY_LONG_LONG val)
 ^~~~~~~~~~~~~~~~~~
src/BTrees/BTreeModuleTemplate.c:132:1: warning: ‘longlong_check’ defined but not used [-Wunused-function]
 longlong_check(PyObject *ob)
 ^~~~~~~~~~~~~~
In file included from src/BTrees/_QFBTree.c:44:0:
src/BTrees/BTreeModuleTemplate.c:209:1: warning: ‘longlong_convert’ defined but not used [-Wunused-function]
 longlong_convert(PyObject *ob, PY_LONG_LONG *value)
 ^~~~~~~~~~~~~~~~
src/BTrees/BTreeModuleTemplate.c:201:1: warning: ‘longlong_as_object’ defined but not used [-Wunused-function]
 longlong_as_object(PY_LONG_LONG val)
 ^~~~~~~~~~~~~~~~~~
src/BTrees/BTreeModuleTemplate.c:132:1: warning: ‘longlong_check’ defined but not used [-Wunused-function]
 longlong_check(PyObject *ob)
 ^~~~~~~~~~~~~~
In file included from src/BTrees/_QLBTree.c:44:0:
src/BTrees/BTreeModuleTemplate.c:132:1: warning: ‘longlong_check’ defined but not used [-Wunused-function]
 longlong_check(PyObject *ob)
 ^~~~~~~~~~~~~~
In file included from src/BTrees/_OQBTree.c:42:0:
src/BTrees/BTreeModuleTemplate.c:209:1: warning: ‘longlong_convert’ defined but not used [-Wunused-function]
 longlong_convert(PyObject *ob, PY_LONG_LONG *value)
 ^~~~~~~~~~~~~~~~
src/BTrees/BTreeModuleTemplate.c:201:1: warning: ‘longlong_as_object’ defined but not used [-Wunused-function]
 longlong_as_object(PY_LONG_LONG val)
 ^~~~~~~~~~~~~~~~~~
warning: no previously-included files found matching 'setup.pyc'
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
zip_safe flag not set; analyzing archive contents...
pycparser.ply.__pycache__.lex.cpython-36: module references __file__
pycparser.ply.__pycache__.lex.cpython-36: module MAY be using inspect.getsourcefile
pycparser.ply.__pycache__.ygen.cpython-36: module references __file__
pycparser.ply.__pycache__.yacc.cpython-36: module references __file__
pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.getsourcefile
pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.stack
no previously-included directories found matching 'terryfy'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'persistent/__pycache__'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'appveyor.yml'
warning: no previously-included files found matching 'buildout.cfg'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no files found matching '*.txt' under directory 'doc'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
  File "build/bdist.linux-x86_64/egg/zodbpickle/tests/pickletester_2.py", line 433
    x = [0, 1L, 2.0, 3.0+0j]
             ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/zodbpickle/pickle_2.py", line 882
    except _Stop, stopinst:
                ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/zodbpickle/pickletools_2.py", line 1803
    print "skipping %r: it doesn't look like an opcode name" % name
                                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("skipping %r: it doesn't look like an opcode name" % name)?

  File "/home/jugmac00/All/output_zope/zopefoundation/zc.relation/.tox/4/py36/eggs/tmpvm4lgsn5/zodbpickle-2.0.0-py3.6-linux-x86_64.egg/zodbpickle/pickle_2.py", line 882
    except _Stop, stopinst:
                ^
SyntaxError: invalid syntax

  File "/home/jugmac00/All/output_zope/zopefoundation/zc.relation/.tox/4/py36/eggs/tmpvm4lgsn5/zodbpickle-2.0.0-py3.6-linux-x86_64.egg/zodbpickle/pickletools_2.py", line 1803
    print "skipping %r: it doesn't look like an opcode name" % name
                                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("skipping %r: it doesn't look like an opcode name" % name)?

  File "/home/jugmac00/All/output_zope/zopefoundation/zc.relation/.tox/4/py36/eggs/tmpvm4lgsn5/zodbpickle-2.0.0-py3.6-linux-x86_64.egg/zodbpickle/tests/pickletester_2.py", line 433
    x = [0, 1L, 2.0, 3.0+0j]
             ^
SyntaxError: invalid syntax

warning: no previously-included files matching '*.pyc' found anywhere in distribution
no previously-included directories found matching 'doc/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files found matching 'setup.pyc'
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
zip_safe flag not set; analyzing archive contents...
pycparser.ply.__pycache__.lex.cpython-36: module references __file__
pycparser.ply.__pycache__.lex.cpython-36: module MAY be using inspect.getsourcefile
pycparser.ply.__pycache__.ygen.cpython-36: module references __file__
pycparser.ply.__pycache__.yacc.cpython-36: module references __file__
pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.getsourcefile
pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.stack
/home/jugmac00/All/output_zope/zopefoundation/zc.relation/src/zc/relation/searchindex.py:379: DeprecationWarning: generator 'Intransitive.getQueries' raised StopIteration
  tuple(q.items()) for q in
/home/jugmac00/All/output_zope/zopefoundation/zc.relation/src/zc/relation/searchindex.py:349: DeprecationWarning: generator 'Intransitive.getQueries' raised StopIteration
  removed):
tox4 run successful for zopefoundation/zc.relation
```

Disclaimer: I do not use this package.

**Comment by icemac** [comment] 2023-04-05 06:14
The deprecation warnings listed above which are caused by this package where fixed in https://github.com/zopefoundation/zc.relation/pull/15.

**Closed as completed by icemac** 2023-04-05 06:14 UTC
